title: ellen-loves-data
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Ellen Rudman
  email: rudman.ellen@gmail.com
  image: assets/img/ellen.jpg
  bio: a highly driven human who loves solving complex problems and running marathons
  github: ""

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 1
  max_level: 5
  list_class: toc
  list_class: toc__list
  sublist_class: toc__sublist

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/